name: Validar nome dos scripts

on: push

jobs:
  validar-scripts:
    runs-on: ubuntu-latest
    steps:
    - name: Verificar nome dos scripts
      run: |
        shopt -s globstar
        for file in scripts/**/*.hql; do
          if [[ ! "$file" =~ ^CHG[0-9]{8}_(D|P|S[1-5]|M[1-9]|[12][0-9]|3[01])_[a-zA-Z0-9_]+\.hql$ ]]; then
            echo "O nome do script $file não segue o padrão especificado."
            exit 1
          fi
        done
