name: validate-script-names
on:
  push:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find scripts
        id: find_scripts
        run: |
          find scripts/ -type f -name "*.hql" > scripts_list.txt
          cat scripts_list.txt

      - name: Validate script names
        run: |
          SCRIPTS=$(cat scripts_list.txt)
          for SCRIPT in $SCRIPTS
          do
             if ! [[ $SCRIPT =~ CHG[0-9]{8}_(D|P|S[1-5]|(M([1-9]|(1[0-9]|2[0-9]|3[0-1]))))_[[:alnum:]_]+\.hql$ ]]
            then
              echo "ERROR: $SCRIPT has an invalid name"
              git rm "$SCRIPT"
              exit 1
            fi
          done

