name: Validar nome de arquivos HQL

on:
  push:
    branches: [main]

jobs:
  validar-nomes-hql:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar nomes de arquivos HQL
        run: |
          pattern='^CHG[0-9]{8}_[DPSM][1-5M]?[0-9]?_[A-Z0-9_]+\.hql$' # define o padrão que o nome do arquivo deve seguir
          for file in ./scripts/*.hql; do # altere o caminho para o diretório onde seus arquivos estão armazenados
            if [[ ! "$file" =~ $pattern ]]; then
              echo "O arquivo $file não segue o padrão de nomenclatura esperado (CHG00000000_D_NOME.hql)"
              exit 1
            fi
          done
